name: Playwright Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options:
        - chromium
        - firefox  
        - webkit
        - all
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'smoke'
        type: choice
        options:
        - smoke
        - regression
        - all

env:
  HEADLESS: true
  BROWSER: chromium
  BASE_URL: https://www.saucedemo.com/
  DEFAULT_TIMEOUT: 30000
  PARALLEL_WORKERS: 4

jobs:
  # Code Quality Checks
  code-quality:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Black (code formatting)
        run: black --check --diff .

      - name: Run isort (import sorting)
        run: isort --check-only --diff .

      - name: Run flake8 (linting)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  # Matrix strategy for multiple browser testing
  playwright-tests:
    name: Playwright Tests
    needs: code-quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        python-version: ['3.9', '3.11']
        exclude:
          - browser: webkit
            python-version: '3.9'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt playwright
      - name: Install system dependencies & Playwright browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 \
            libffi8 \
            libx264-164 \
            libopus0 \
            libwoff1 \
            libharfbuzz-icu0 \
            libgstreamer-gl1.0-0 \
            libgstreamer-plugins-bad1.0-0 || true
          playwright install ${{ matrix.browser }}
      - name: Run tests
        run: |
          pytest tests/ \
            -m smoke \
            --browser=${{ matrix.browser }} \
            --headless \
            --video=on \
            --screenshot=on \
            --html=reports/smoke-report-${{ matrix.browser }}.html \
            --self-contained-html \
            --junitxml=reports/junit-smoke-${{ matrix.browser }}.xml \
            -n ${{ env.PARALLEL_WORKERS }} \
            --tb=short
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: true
          CI: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}-${{ matrix.python-version }}
          path: |
            reports/
            screenshots/
            test-results/
          retention-days: 30

  # BDD Tests (separate job)
  bdd-tests:
    name: BDD Tests
    needs: code-quality
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Python package
        run: pip install playwright

      # Fix Ubuntu 24.04 dependency issues
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 \
            libffi8 \
            libx264-164 \
            libopus0 \
            libwoff1 \
            libharfbuzz-icu0 \
            libgstreamer-gl1.0-0 \
            libgstreamer-plugins-bad1.0-0

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Run BDD tests
        run: |
          pytest step_definitions/ \
            --gherkin-terminal-reporter \
            --browser=chromium \
            --headless \
            --html=reports/bdd-report.html \
            --self-contained-html
        env:
          BROWSER: chromium
          HEADLESS: true
          CI: true

      - name: Upload BDD reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bdd-test-reports
          path: reports/
          retention-days: 30
