name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]  # Run tests on all 3 browsers
    timeout-minutes: 40

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install --with-deps

      - name: Run E2E Tests
        run: |
          pytest tests/ \
            --browser ${{ matrix.browser }} \
            --junitxml=reports/junit-${{ matrix.browser }}.xml \
            --html=reports/html-${{ matrix.browser }}.html \
            -v --capture=sys
        env:
          BASE_URL: https://www.saucedemo.com
          BROWSER: ${{ matrix.browser }}
          HEADLESS: 'True'
          DEBUG: 'False'

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-reports-${{ matrix.browser }}
          path: |
            reports/*.html
            reports/*.xml
            screenshots/*.png
