name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-22.04   # Stable runner for Playwright
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    timeout-minutes: 40

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install OS dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libasound2 \
            libx11-xcb1 \
            libxshmfence1 \
            libxfixes3 \
            libxrender1 \
            libffi-dev \
            libjpeg-dev \
            libpng-dev \
            libx264-160 \
            wget \
            curl \
            ca-certificates

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright and Browsers
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Run E2E Tests
        run: |
          mkdir -p reports screenshots
          pytest tests/ \
            --browser ${{ matrix.browser }} \
            --junitxml=reports/junit-${{ matrix.browser }}.xml \
            --html=reports/html-${{ matrix.browser }}.html \
            -v --capture=sys
        env:
          BASE_URL: https://www.saucedemo.com
          BROWSER: ${{ matrix.browser }}
          HEADLESS: 'True'
          DEBUG: 'False'

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-reports-${{ matrix.browser }}
          path: |
            reports/*.html
            reports/*.xml
            screenshots/*.png
