name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false
    timeout-minutes: 40
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install --with-deps  # Installs browsers and system dependencies

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run E2E Tests
        run: |
          python -m pytest tests/ \
            --browser ${{ matrix.browser }} \
            --junitxml=reports/junit-${{ matrix.browser }}.xml \
            --html=reports/html-${{ matrix.browser }}.html \
            -v --capture=sys
        env:
          BASE_URL: https://www.saucedemo.com
          BROWSER: ${{ matrix.browser }}
          HEADLESS: 'True'
          DEBUG: 'False'

      - name: List generated files (for debugging)
        if: always()
        run: |
          ls -la reports/ || echo "No reports directory"
          find . -name "*.xml" -o -name "*.html" -o -name "*.png" | head -10 || echo "No test files found"

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-reports-${{ matrix.browser }}
          path: |
            reports/
            screenshots/